# Generated by Django 5.0.4 on 2024-05-23 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.UUIDField(primary_key=True, serialize=False)),
                ('plot_lot_number', models.CharField(max_length=100)),
                ('plot_sale_order', models.CharField(max_length=100)),
                ('plot_type', models.CharField(max_length=100)),
                ('plot_size', models.FloatField()),
                ('plot_upload_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlotCase',
            fields=[
                ('case_number', models.UUIDField(primary_key=True, serialize=False)),
                ('case_province', models.CharField(max_length=100)),
                ('case_district', models.CharField(max_length=100)),
                ('case_sub_district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlotPrice',
            fields=[
                ('price_plot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.plot')),
                ('price_professional', models.FloatField()),
                ('price_enforcer', models.FloatField()),
                ('price_legalgov', models.FloatField()),
                ('price_committee', models.FloatField()),
                ('price_predictive', models.FloatField()),
                ('price_real', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plot')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_case_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plotcase'),
        ),
        migrations.CreateModel(
            name='PlotMap',
            fields=[
                ('map_id', models.UUIDField(primary_key=True, serialize=False)),
                ('map_link', models.CharField(max_length=255)),
                ('map_plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotPicture',
            fields=[
                ('picture_id', models.UUIDField(primary_key=True, serialize=False)),
                ('picture_link', models.CharField(max_length=100)),
                ('picture_plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotSale',
            fields=[
                ('sale_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sale_date', models.CharField(max_length=100)),
                ('sale_status', models.CharField(max_length=100)),
                ('sale_plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plot')),
            ],
        ),
    ]
