# Generated by Django 5.0.4 on 2024-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotcase',
            name='case_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
