# Generated by Django 5.0.4 on 2024-05-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plotcase_case_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_plot_id',
            new_name='favorite_plot',
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='plot_case_number',
            new_name='plot_case',
        ),
        migrations.RenameField(
            model_name='plotmap',
            old_name='map_plot_id',
            new_name='map_plot',
        ),
        migrations.RenameField(
            model_name='plotpicture',
            old_name='picture_plot_id',
            new_name='picture_plot',
        ),
        migrations.RenameField(
            model_name='plotprice',
            old_name='price_plot_id',
            new_name='price_plot',
        ),
        migrations.RenameField(
            model_name='plotsale',
            old_name='sale_plot_id',
            new_name='sale_plot',
        ),
    ]
