# Generated by Django 5.0.4 on 2024-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_favorite_plot_id_favorite_favorite_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotprice',
            name='price_committee',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_legalgov',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_predictive',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_professional',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_real',
            field=models.FloatField(blank=True),
        ),
    ]
