# Generated by Django 5.0.4 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plotprice_price_committee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotprice',
            name='price_committee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_enforcer',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_legalgov',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_predictive',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_professional',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plotprice',
            name='price_real',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
